FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
RUN npx prisma generate --schema=db/schema.prisma
# migrate deploy применяет миграции при старте
CMD ["sh", "-c", "npx prisma migrate deploy --schema=db/schema.prisma && node api/index.js"]
